### ISSUE TITLE
Overall team winrate should be shown

### ISSUE THREAD

**Issue by uv48uson** [pardinensis/Outdraft#3]
The tool should show a overall team winrate. This winrate should be a combination of all matchups, synergies, player assignment etc.
The overall winrate helps users to assess thier draft in hindseight. This especially enables practise drafting.

**Comment by pardinensis** [comment]
Implemented in affa6373771c492d0cce2f23c25e54e1bda51ffe

The program now always shows the expected win rate for the drafting team (regardless of the current draft state)
